#### Assignment 3: Neural Networks  
##### Group 1  
###### 1. Chetna Manchanda: 100943852  
###### 2. Rounak Virmani: 100911456  
###### 3. Kandarp Joshi: 100943058  
###### 4. Grifith Pradeep Pereira: 1009
###### 4. Kaizaan Keshwani: 100930806  
###### 4. Marium memon: 10098503  4

#### In this analysis, we aim to build a Neural Network model using the 'drugdataset.csv' provided by John Hughes using patient attributes such as age, sex, blood pressure, cholesterol levels, and sodium-to-potassium ratio.
#### The primary objective is to evaluate the performance of the Neural Network in terms of accuracy, precision, recall, and F1-score, and compare it against a previously developed Logistic Regression model.

In [3]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
# Load the dataset
drugData = pd.read_csv('drugdataset.csv')

#Display 5 rows of Data
drugData.head()


Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    1   2            1   25.355  drugY
1   47    0   1            1   13.093  drugC
2   47    0   1            1   10.114  drugC
3   28    1   0            1    7.798  drugX
4   61    1   1            1   18.043  drugY

In [5]:
#Generate key statistics using: describe()
drugData.describe().T

count       mean        std     min      25%      50%    75%  \
Age          200.0  44.315000  16.544315  15.000  31.0000  45.0000  58.00   
Sex          200.0   0.480000   0.500854   0.000   0.0000   0.0000   1.00   
BP           200.0   1.090000   0.821752   0.000   0.0000   1.0000   2.00   
Cholesterol  200.0   0.515000   0.501029   0.000   0.0000   1.0000   1.00   
Na_to_K      200.0  16.084485   7.223956   6.269  10.4455  13.9365  19.38   

                max  
Age          74.000  
Sex           1.000  
BP            2.000  
Cholesterol   1.000  
Na_to_K      38.247

In [6]:
#Identify number of Classes (i.e. drugs)
drugData.Drug.unique()

array(['drugY', 'drugC', 'drugX', 'drugA', 'drugB'], dtype=object)

In [7]:
# create x and y variables
X = drugData.drop('Drug', axis=1).to_numpy() # Drop 'Drug' column and convert remaining data to a NumPy array.
y = drugData['Drug'].to_numpy() # Convert 'Drug' column to a NumPy array as target labels.

In [8]:
# Create Train and Test datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, stratify=y, test_size=0.20, random_state=100
)
# Scale the data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(X_train)
x_test2 = sc.transform(X_test)

In [9]:
# Script for Neural Network
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(
    hidden_layer_sizes=(5, 4, 5), 
    activation='relu', 
    solver='adam', 
    max_iter=10000, 
    random_state=100
)
mlp.fit(x_train2, y_train)
predictions = mlp.predict(x_test2)

In [10]:
# Evaluation Report and Matrix
from sklearn.metrics import classification_report, confusion_matrix
# Define target names
target_names = drugData['Drug'].unique()
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions, target_names=target_names))

[[ 5  0  0  0  0]
 [ 0  2  0  0  1]
 [ 0  0  3  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  1 17]]
              precision    recall  f1-score   support

       drugY       1.00      1.00      1.00         5
       drugC       1.00      0.67      0.80         3
       drugX       1.00      1.00      1.00         3
       drugA       0.92      1.00      0.96        11
       drugB       0.94      0.94      0.94        18

    accuracy                           0.95        40
   macro avg       0.97      0.92      0.94        40
weighted avg       0.95      0.95      0.95        40

